// Generated by Bisonc++ V4.09.02 on Sun, 01 May 2016 17:32:37 +0200

// $insert class.ih
#include "interpretParser.ih"

// The FIRST element of SR arrays shown below uses `d_type', defining the
// state's type, and `d_lastIdx' containing the last element's index. If
// d_lastIdx contains the REQ_TOKEN bitflag (see below) then the state needs
// a token: if in this state d_token__ is _UNDETERMINED_, nextToken() will be
// called

// The LAST element of SR arrays uses `d_token' containing the last retrieved
// token to speed up the (linear) seach.  Except for the first element of SR
// arrays, the field `d_action' is used to determine what to do next. If
// positive, it represents the next state (used with SHIFT); if zero, it
// indicates `ACCEPT', if negative, -d_action represents the number of the
// rule to reduce to.

// `lookup()' tries to find d_token__ in the current SR array. If it fails, and
// there is no default reduction UNEXPECTED_TOKEN__ is thrown, which is then
// caught by the error-recovery function.

// The error-recovery function will pop elements off the stack until a state
// having bit flag ERR_ITEM is found. This state has a transition on _error_
// which is applied. In this _error_ state, while the current token is not a
// proper continuation, new tokens are obtained by nextToken(). If such a
// token is found, error recovery is successful and the token is
// handled according to the error state's SR table and parsing continues.
// During error recovery semantic actions are ignored.

// A state flagged with the DEF_RED flag will perform a default
// reduction if no other continuations are available for the current token.

// The ACCEPT STATE never shows a default reduction: when it is reached the
// parser returns ACCEPT(). During the grammar
// analysis phase a default reduction may have been defined, but it is
// removed during the state-definition phase.

// So:
//      s_x[] = 
//      {
//                  [_field_1_]         [_field_2_]
//
// First element:   {state-type,        idx of last element},
// Other elements:  {required token,    action to perform},
//                                      ( < 0: reduce, 
//                                          0: ACCEPT,
//                                        > 0: next state)
// Last element:    {set to d_token__,    action to perform}
//      }

// When the --thread-safe option is specified, all static data are defined as
// const. If --thread-safe is not provided, the state-tables are not defined
// as const, since the lookup() function below will modify them


namespace // anonymous
{
    char const author[] = "Frank B. Brokken (f.b.brokken@rug.nl)";

    enum 
    {
        STACK_EXPANSION = 5     // size to expand the state-stack with when
                                // full
    };

    enum ReservedTokens
    {
        PARSE_ACCEPT     = 0,   // `ACCEPT' TRANSITION
        _UNDETERMINED_   = -2,
        _EOF_            = -1,
        _error_          = 256
    };
    enum StateType       // modify statetype/data.cc when this enum changes
    {
        NORMAL,
        ERR_ITEM,
        REQ_TOKEN,
        ERR_REQ,    // ERR_ITEM | REQ_TOKEN
        DEF_RED,    // state having default reduction
        ERR_DEF,    // ERR_ITEM | DEF_RED
        REQ_DEF,    // REQ_TOKEN | DEF_RED
        ERR_REQ_DEF // ERR_ITEM | REQ_TOKEN | DEF_RED
    };    
    struct PI__     // Production Info
    {
        size_t d_nonTerm; // identification number of this production's
                            // non-terminal 
        size_t d_size;    // number of elements in this production 
    };

    struct SR__     // Shift Reduce info, see its description above
    {
        union
        {
            int _field_1_;      // initializer, allowing initializations 
                                // of the SR s_[] arrays
            int d_type;
            int d_token;
        };
        union
        {
            int _field_2_;

            int d_lastIdx;          // if negative, the state uses SHIFT
            int d_action;           // may be negative (reduce), 
                                    // postive (shift), or 0 (accept)
            size_t d_errorState;    // used with Error states
        };
    };

    // $insert staticdata
    
// Productions Info Records:
PI__ const s_productionInfo[] = 
{
     {0, 0}, // not used: reduction values are negative
     {297, 1}, // 1: start ->  utasitas
     {298, 4}, // 2: utasitas (MOV) ->  MOV elsoarg VESSZO ertek
     {298, 4}, // 3: utasitas (ADD) ->  ADD elsoarg VESSZO ertek
     {298, 4}, // 4: utasitas (SUB) ->  SUB elsoarg VESSZO ertek
     {298, 4}, // 5: utasitas (CMP) ->  CMP ertek VESSZO ertek
     {298, 4}, // 6: utasitas (AND) ->  AND elsoarg VESSZO ertek
     {298, 4}, // 7: utasitas (OR) ->  OR elsoarg VESSZO ertek
     {298, 4}, // 8: utasitas (XOR) ->  XOR elsoarg VESSZO ertek
     {298, 2}, // 9: utasitas (MUL) ->  MUL elsoarg
     {298, 2}, // 10: utasitas (DIV) ->  DIV elsoarg
     {298, 2}, // 11: utasitas (INC) ->  INC elsoarg
     {298, 2}, // 12: utasitas (DEC) ->  DEC elsoarg
     {298, 2}, // 13: utasitas (NOT) ->  NOT elsoarg
     {298, 2}, // 14: utasitas (PUSH) ->  PUSH elsoarg
     {298, 2}, // 15: utasitas (POP) ->  POP elsoarg
     {298, 2}, // 16: utasitas (JMP) ->  JMP AZONOSITO
     {298, 2}, // 17: utasitas (JA) ->  JA AZONOSITO
     {298, 2}, // 18: utasitas (JB) ->  JB AZONOSITO
     {298, 2}, // 19: utasitas (JE) ->  JE AZONOSITO
     {298, 2}, // 20: utasitas (JZ) ->  JZ AZONOSITO
     {298, 2}, // 21: utasitas (JNA) ->  JNA AZONOSITO
     {298, 2}, // 22: utasitas (JNB) ->  JNB AZONOSITO
     {298, 2}, // 23: utasitas (JNE) ->  JNE AZONOSITO
     {298, 2}, // 24: utasitas (JNZ) ->  JNZ AZONOSITO
     {298, 2}, // 25: utasitas (CALL) ->  CALL AZONOSITO
     {298, 1}, // 26: utasitas (RET) ->  RET
     {299, 1}, // 27: elsoarg (REGISZTER) ->  REGISZTER
     {299, 3}, // 28: elsoarg (NYITOSZOGZAROJEL) ->  NYITOSZOGZAROJEL ertek CSUKOSZOGZAROJEL
     {300, 3}, // 29: ertek (NYITOZAROJEL) ->  NYITOZAROJEL ertek CSUKOZAROJEL
     {300, 3}, // 30: ertek (MULTIPLY) ->  ertek MULTIPLY ertek
     {300, 3}, // 31: ertek (DIVIDE) ->  ertek DIVIDE ertek
     {300, 3}, // 32: ertek (PLUS) ->  ertek PLUS ertek
     {300, 3}, // 33: ertek (MINUS) ->  ertek MINUS ertek
     {300, 1}, // 34: ertek (REGISZTER) ->  REGISZTER
     {300, 1}, // 35: ertek (AZONOSITO) ->  AZONOSITO
     {300, 1}, // 36: ertek (SZAM) ->  SZAM
     {301, 1}, // 37: start_$ ->  start
};

// State info and SR__ transitions for each state.


SR__ s_0[] =
{
    { { REQ_TOKEN}, { 28} },            
    { {       297}, {  1} }, // start   
    { {       298}, {  2} }, // utasitas
    { {       264}, {  3} }, // MOV     
    { {       265}, {  4} }, // ADD     
    { {       266}, {  5} }, // SUB     
    { {       267}, {  6} }, // CMP     
    { {       268}, {  7} }, // AND     
    { {       269}, {  8} }, // OR      
    { {       270}, {  9} }, // XOR     
    { {       271}, { 10} }, // MUL     
    { {       272}, { 11} }, // DIV     
    { {       273}, { 12} }, // INC     
    { {       274}, { 13} }, // DEC     
    { {       275}, { 14} }, // NOT     
    { {       276}, { 15} }, // PUSH    
    { {       277}, { 16} }, // POP     
    { {       278}, { 17} }, // JMP     
    { {       279}, { 18} }, // JA      
    { {       280}, { 19} }, // JB      
    { {       281}, { 20} }, // JE      
    { {       282}, { 21} }, // JZ      
    { {       283}, { 22} }, // JNA     
    { {       284}, { 23} }, // JNB     
    { {       285}, { 24} }, // JNE     
    { {       286}, { 25} }, // JNZ     
    { {       287}, { 26} }, // CALL    
    { {       288}, { 27} }, // RET     
    { {         0}, {  0} },            
};

SR__ s_1[] =
{
    { { REQ_TOKEN}, {            2} }, 
    { {     _EOF_}, { PARSE_ACCEPT} }, 
    { {         0}, {            0} }, 
};

SR__ s_2[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -1} }, 
};

SR__ s_3[] =
{
    { { REQ_TOKEN}, {  4} },                    
    { {       299}, { 28} }, // elsoarg         
    { {       293}, { 29} }, // REGISZTER       
    { {       261}, { 30} }, // NYITOSZOGZAROJEL
    { {         0}, {  0} },                    
};

SR__ s_4[] =
{
    { { REQ_TOKEN}, {  4} },                    
    { {       299}, { 31} }, // elsoarg         
    { {       293}, { 29} }, // REGISZTER       
    { {       261}, { 30} }, // NYITOSZOGZAROJEL
    { {         0}, {  0} },                    
};

SR__ s_5[] =
{
    { { REQ_TOKEN}, {  4} },                    
    { {       299}, { 32} }, // elsoarg         
    { {       293}, { 29} }, // REGISZTER       
    { {       261}, { 30} }, // NYITOSZOGZAROJEL
    { {         0}, {  0} },                    
};

SR__ s_6[] =
{
    { { REQ_TOKEN}, {  6} },                
    { {       300}, { 33} }, // ertek       
    { {       259}, { 34} }, // NYITOZAROJEL
    { {       293}, { 35} }, // REGISZTER   
    { {       258}, { 36} }, // AZONOSITO   
    { {       257}, { 37} }, // SZAM        
    { {         0}, {  0} },                
};

SR__ s_7[] =
{
    { { REQ_TOKEN}, {  4} },                    
    { {       299}, { 38} }, // elsoarg         
    { {       293}, { 29} }, // REGISZTER       
    { {       261}, { 30} }, // NYITOSZOGZAROJEL
    { {         0}, {  0} },                    
};

SR__ s_8[] =
{
    { { REQ_TOKEN}, {  4} },                    
    { {       299}, { 39} }, // elsoarg         
    { {       293}, { 29} }, // REGISZTER       
    { {       261}, { 30} }, // NYITOSZOGZAROJEL
    { {         0}, {  0} },                    
};

SR__ s_9[] =
{
    { { REQ_TOKEN}, {  4} },                    
    { {       299}, { 40} }, // elsoarg         
    { {       293}, { 29} }, // REGISZTER       
    { {       261}, { 30} }, // NYITOSZOGZAROJEL
    { {         0}, {  0} },                    
};

SR__ s_10[] =
{
    { { REQ_TOKEN}, {  4} },                    
    { {       299}, { 41} }, // elsoarg         
    { {       293}, { 29} }, // REGISZTER       
    { {       261}, { 30} }, // NYITOSZOGZAROJEL
    { {         0}, {  0} },                    
};

SR__ s_11[] =
{
    { { REQ_TOKEN}, {  4} },                    
    { {       299}, { 42} }, // elsoarg         
    { {       293}, { 29} }, // REGISZTER       
    { {       261}, { 30} }, // NYITOSZOGZAROJEL
    { {         0}, {  0} },                    
};

SR__ s_12[] =
{
    { { REQ_TOKEN}, {  4} },                    
    { {       299}, { 43} }, // elsoarg         
    { {       293}, { 29} }, // REGISZTER       
    { {       261}, { 30} }, // NYITOSZOGZAROJEL
    { {         0}, {  0} },                    
};

SR__ s_13[] =
{
    { { REQ_TOKEN}, {  4} },                    
    { {       299}, { 44} }, // elsoarg         
    { {       293}, { 29} }, // REGISZTER       
    { {       261}, { 30} }, // NYITOSZOGZAROJEL
    { {         0}, {  0} },                    
};

SR__ s_14[] =
{
    { { REQ_TOKEN}, {  4} },                    
    { {       299}, { 45} }, // elsoarg         
    { {       293}, { 29} }, // REGISZTER       
    { {       261}, { 30} }, // NYITOSZOGZAROJEL
    { {         0}, {  0} },                    
};

SR__ s_15[] =
{
    { { REQ_TOKEN}, {  4} },                    
    { {       299}, { 46} }, // elsoarg         
    { {       293}, { 29} }, // REGISZTER       
    { {       261}, { 30} }, // NYITOSZOGZAROJEL
    { {         0}, {  0} },                    
};

SR__ s_16[] =
{
    { { REQ_TOKEN}, {  4} },                    
    { {       299}, { 47} }, // elsoarg         
    { {       293}, { 29} }, // REGISZTER       
    { {       261}, { 30} }, // NYITOSZOGZAROJEL
    { {         0}, {  0} },                    
};

SR__ s_17[] =
{
    { { REQ_TOKEN}, {  2} },             
    { {       258}, { 48} }, // AZONOSITO
    { {         0}, {  0} },             
};

SR__ s_18[] =
{
    { { REQ_TOKEN}, {  2} },             
    { {       258}, { 49} }, // AZONOSITO
    { {         0}, {  0} },             
};

SR__ s_19[] =
{
    { { REQ_TOKEN}, {  2} },             
    { {       258}, { 50} }, // AZONOSITO
    { {         0}, {  0} },             
};

SR__ s_20[] =
{
    { { REQ_TOKEN}, {  2} },             
    { {       258}, { 51} }, // AZONOSITO
    { {         0}, {  0} },             
};

SR__ s_21[] =
{
    { { REQ_TOKEN}, {  2} },             
    { {       258}, { 52} }, // AZONOSITO
    { {         0}, {  0} },             
};

SR__ s_22[] =
{
    { { REQ_TOKEN}, {  2} },             
    { {       258}, { 53} }, // AZONOSITO
    { {         0}, {  0} },             
};

SR__ s_23[] =
{
    { { REQ_TOKEN}, {  2} },             
    { {       258}, { 54} }, // AZONOSITO
    { {         0}, {  0} },             
};

SR__ s_24[] =
{
    { { REQ_TOKEN}, {  2} },             
    { {       258}, { 55} }, // AZONOSITO
    { {         0}, {  0} },             
};

SR__ s_25[] =
{
    { { REQ_TOKEN}, {  2} },             
    { {       258}, { 56} }, // AZONOSITO
    { {         0}, {  0} },             
};

SR__ s_26[] =
{
    { { REQ_TOKEN}, {  2} },             
    { {       258}, { 57} }, // AZONOSITO
    { {         0}, {  0} },             
};

SR__ s_27[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -26} }, 
};

SR__ s_28[] =
{
    { { REQ_TOKEN}, {  2} },          
    { {       263}, { 58} }, // VESSZO
    { {         0}, {  0} },          
};

SR__ s_29[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -27} }, 
};

SR__ s_30[] =
{
    { { REQ_TOKEN}, {  6} },                
    { {       300}, { 59} }, // ertek       
    { {       259}, { 34} }, // NYITOZAROJEL
    { {       293}, { 35} }, // REGISZTER   
    { {       258}, { 36} }, // AZONOSITO   
    { {       257}, { 37} }, // SZAM        
    { {         0}, {  0} },                
};

SR__ s_31[] =
{
    { { REQ_TOKEN}, {  2} },          
    { {       263}, { 60} }, // VESSZO
    { {         0}, {  0} },          
};

SR__ s_32[] =
{
    { { REQ_TOKEN}, {  2} },          
    { {       263}, { 61} }, // VESSZO
    { {         0}, {  0} },          
};

SR__ s_33[] =
{
    { { REQ_TOKEN}, {  6} },            
    { {       263}, { 62} }, // VESSZO  
    { {       291}, { 63} }, // MULTIPLY
    { {       292}, { 64} }, // DIVIDE  
    { {       289}, { 65} }, // PLUS    
    { {       290}, { 66} }, // MINUS   
    { {         0}, {  0} },            
};

SR__ s_34[] =
{
    { { REQ_TOKEN}, {  6} },                
    { {       300}, { 67} }, // ertek       
    { {       259}, { 34} }, // NYITOZAROJEL
    { {       293}, { 35} }, // REGISZTER   
    { {       258}, { 36} }, // AZONOSITO   
    { {       257}, { 37} }, // SZAM        
    { {         0}, {  0} },                
};

SR__ s_35[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -34} }, 
};

SR__ s_36[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -35} }, 
};

SR__ s_37[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -36} }, 
};

SR__ s_38[] =
{
    { { REQ_TOKEN}, {  2} },          
    { {       263}, { 68} }, // VESSZO
    { {         0}, {  0} },          
};

SR__ s_39[] =
{
    { { REQ_TOKEN}, {  2} },          
    { {       263}, { 69} }, // VESSZO
    { {         0}, {  0} },          
};

SR__ s_40[] =
{
    { { REQ_TOKEN}, {  2} },          
    { {       263}, { 70} }, // VESSZO
    { {         0}, {  0} },          
};

SR__ s_41[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -9} }, 
};

SR__ s_42[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -10} }, 
};

SR__ s_43[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -11} }, 
};

SR__ s_44[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -12} }, 
};

SR__ s_45[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -13} }, 
};

SR__ s_46[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -14} }, 
};

SR__ s_47[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -15} }, 
};

SR__ s_48[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -16} }, 
};

SR__ s_49[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -17} }, 
};

SR__ s_50[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -18} }, 
};

SR__ s_51[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -19} }, 
};

SR__ s_52[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -20} }, 
};

SR__ s_53[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -21} }, 
};

SR__ s_54[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -22} }, 
};

SR__ s_55[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -23} }, 
};

SR__ s_56[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -24} }, 
};

SR__ s_57[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -25} }, 
};

SR__ s_58[] =
{
    { { REQ_TOKEN}, {  6} },                
    { {       300}, { 71} }, // ertek       
    { {       259}, { 34} }, // NYITOZAROJEL
    { {       293}, { 35} }, // REGISZTER   
    { {       258}, { 36} }, // AZONOSITO   
    { {       257}, { 37} }, // SZAM        
    { {         0}, {  0} },                
};

SR__ s_59[] =
{
    { { REQ_TOKEN}, {  6} },                    
    { {       262}, { 72} }, // CSUKOSZOGZAROJEL
    { {       291}, { 63} }, // MULTIPLY        
    { {       292}, { 64} }, // DIVIDE          
    { {       289}, { 65} }, // PLUS            
    { {       290}, { 66} }, // MINUS           
    { {         0}, {  0} },                    
};

SR__ s_60[] =
{
    { { REQ_TOKEN}, {  6} },                
    { {       300}, { 73} }, // ertek       
    { {       259}, { 34} }, // NYITOZAROJEL
    { {       293}, { 35} }, // REGISZTER   
    { {       258}, { 36} }, // AZONOSITO   
    { {       257}, { 37} }, // SZAM        
    { {         0}, {  0} },                
};

SR__ s_61[] =
{
    { { REQ_TOKEN}, {  6} },                
    { {       300}, { 74} }, // ertek       
    { {       259}, { 34} }, // NYITOZAROJEL
    { {       293}, { 35} }, // REGISZTER   
    { {       258}, { 36} }, // AZONOSITO   
    { {       257}, { 37} }, // SZAM        
    { {         0}, {  0} },                
};

SR__ s_62[] =
{
    { { REQ_TOKEN}, {  6} },                
    { {       300}, { 75} }, // ertek       
    { {       259}, { 34} }, // NYITOZAROJEL
    { {       293}, { 35} }, // REGISZTER   
    { {       258}, { 36} }, // AZONOSITO   
    { {       257}, { 37} }, // SZAM        
    { {         0}, {  0} },                
};

SR__ s_63[] =
{
    { { REQ_TOKEN}, {  6} },                
    { {       300}, { 76} }, // ertek       
    { {       259}, { 34} }, // NYITOZAROJEL
    { {       293}, { 35} }, // REGISZTER   
    { {       258}, { 36} }, // AZONOSITO   
    { {       257}, { 37} }, // SZAM        
    { {         0}, {  0} },                
};

SR__ s_64[] =
{
    { { REQ_TOKEN}, {  6} },                
    { {       300}, { 77} }, // ertek       
    { {       259}, { 34} }, // NYITOZAROJEL
    { {       293}, { 35} }, // REGISZTER   
    { {       258}, { 36} }, // AZONOSITO   
    { {       257}, { 37} }, // SZAM        
    { {         0}, {  0} },                
};

SR__ s_65[] =
{
    { { REQ_TOKEN}, {  6} },                
    { {       300}, { 78} }, // ertek       
    { {       259}, { 34} }, // NYITOZAROJEL
    { {       293}, { 35} }, // REGISZTER   
    { {       258}, { 36} }, // AZONOSITO   
    { {       257}, { 37} }, // SZAM        
    { {         0}, {  0} },                
};

SR__ s_66[] =
{
    { { REQ_TOKEN}, {  6} },                
    { {       300}, { 79} }, // ertek       
    { {       259}, { 34} }, // NYITOZAROJEL
    { {       293}, { 35} }, // REGISZTER   
    { {       258}, { 36} }, // AZONOSITO   
    { {       257}, { 37} }, // SZAM        
    { {         0}, {  0} },                
};

SR__ s_67[] =
{
    { { REQ_TOKEN}, {  6} },                
    { {       260}, { 80} }, // CSUKOZAROJEL
    { {       291}, { 63} }, // MULTIPLY    
    { {       292}, { 64} }, // DIVIDE      
    { {       289}, { 65} }, // PLUS        
    { {       290}, { 66} }, // MINUS       
    { {         0}, {  0} },                
};

SR__ s_68[] =
{
    { { REQ_TOKEN}, {  6} },                
    { {       300}, { 81} }, // ertek       
    { {       259}, { 34} }, // NYITOZAROJEL
    { {       293}, { 35} }, // REGISZTER   
    { {       258}, { 36} }, // AZONOSITO   
    { {       257}, { 37} }, // SZAM        
    { {         0}, {  0} },                
};

SR__ s_69[] =
{
    { { REQ_TOKEN}, {  6} },                
    { {       300}, { 82} }, // ertek       
    { {       259}, { 34} }, // NYITOZAROJEL
    { {       293}, { 35} }, // REGISZTER   
    { {       258}, { 36} }, // AZONOSITO   
    { {       257}, { 37} }, // SZAM        
    { {         0}, {  0} },                
};

SR__ s_70[] =
{
    { { REQ_TOKEN}, {  6} },                
    { {       300}, { 83} }, // ertek       
    { {       259}, { 34} }, // NYITOZAROJEL
    { {       293}, { 35} }, // REGISZTER   
    { {       258}, { 36} }, // AZONOSITO   
    { {       257}, { 37} }, // SZAM        
    { {         0}, {  0} },                
};

SR__ s_71[] =
{
    { { REQ_DEF}, {  5} },            
    { {     291}, { 63} }, // MULTIPLY
    { {     292}, { 64} }, // DIVIDE  
    { {     289}, { 65} }, // PLUS    
    { {     290}, { 66} }, // MINUS   
    { {       0}, { -2} },            
};

SR__ s_72[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -28} }, 
};

SR__ s_73[] =
{
    { { REQ_DEF}, {  5} },            
    { {     291}, { 63} }, // MULTIPLY
    { {     292}, { 64} }, // DIVIDE  
    { {     289}, { 65} }, // PLUS    
    { {     290}, { 66} }, // MINUS   
    { {       0}, { -3} },            
};

SR__ s_74[] =
{
    { { REQ_DEF}, {  5} },            
    { {     291}, { 63} }, // MULTIPLY
    { {     292}, { 64} }, // DIVIDE  
    { {     289}, { 65} }, // PLUS    
    { {     290}, { 66} }, // MINUS   
    { {       0}, { -4} },            
};

SR__ s_75[] =
{
    { { REQ_DEF}, {  5} },            
    { {     291}, { 63} }, // MULTIPLY
    { {     292}, { 64} }, // DIVIDE  
    { {     289}, { 65} }, // PLUS    
    { {     290}, { 66} }, // MINUS   
    { {       0}, { -5} },            
};

SR__ s_76[] =
{
    { { REQ_DEF}, {   1} }, 
    { {       0}, { -30} }, 
};

SR__ s_77[] =
{
    { { REQ_DEF}, {   1} }, 
    { {       0}, { -31} }, 
};

SR__ s_78[] =
{
    { { REQ_DEF}, {   3} },            
    { {     291}, {  63} }, // MULTIPLY
    { {     292}, {  64} }, // DIVIDE  
    { {       0}, { -32} },            
};

SR__ s_79[] =
{
    { { REQ_DEF}, {   3} },            
    { {     291}, {  63} }, // MULTIPLY
    { {     292}, {  64} }, // DIVIDE  
    { {       0}, { -33} },            
};

SR__ s_80[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -29} }, 
};

SR__ s_81[] =
{
    { { REQ_DEF}, {  5} },            
    { {     291}, { 63} }, // MULTIPLY
    { {     292}, { 64} }, // DIVIDE  
    { {     289}, { 65} }, // PLUS    
    { {     290}, { 66} }, // MINUS   
    { {       0}, { -6} },            
};

SR__ s_82[] =
{
    { { REQ_DEF}, {  5} },            
    { {     291}, { 63} }, // MULTIPLY
    { {     292}, { 64} }, // DIVIDE  
    { {     289}, { 65} }, // PLUS    
    { {     290}, { 66} }, // MINUS   
    { {       0}, { -7} },            
};

SR__ s_83[] =
{
    { { REQ_DEF}, {  5} },            
    { {     291}, { 63} }, // MULTIPLY
    { {     292}, { 64} }, // DIVIDE  
    { {     289}, { 65} }, // PLUS    
    { {     290}, { 66} }, // MINUS   
    { {       0}, { -8} },            
};


// State array:
SR__ *s_state[] =
{
  s_0,  s_1,  s_2,  s_3,  s_4,  s_5,  s_6,  s_7,  s_8,  s_9,
  s_10,  s_11,  s_12,  s_13,  s_14,  s_15,  s_16,  s_17,  s_18,  s_19,
  s_20,  s_21,  s_22,  s_23,  s_24,  s_25,  s_26,  s_27,  s_28,  s_29,
  s_30,  s_31,  s_32,  s_33,  s_34,  s_35,  s_36,  s_37,  s_38,  s_39,
  s_40,  s_41,  s_42,  s_43,  s_44,  s_45,  s_46,  s_47,  s_48,  s_49,
  s_50,  s_51,  s_52,  s_53,  s_54,  s_55,  s_56,  s_57,  s_58,  s_59,
  s_60,  s_61,  s_62,  s_63,  s_64,  s_65,  s_66,  s_67,  s_68,  s_69,
  s_70,  s_71,  s_72,  s_73,  s_74,  s_75,  s_76,  s_77,  s_78,  s_79,
  s_80,  s_81,  s_82,  s_83,
};

} // anonymous namespace ends



// If the parsing function call uses arguments, then provide an overloaded
// function.  The code below doesn't rely on parameters, so no arguments are
// required.  Furthermore, parse uses a function try block to allow us to do
// ACCEPT and ABORT from anywhere, even from within members called by actions,
// simply throwing the appropriate exceptions.

interpretParserBase::interpretParserBase()
:
    d_stackIdx__(-1),
    // $insert debuginit
    d_debug__(false),
    d_nErrors__(0),
    // $insert requiredtokens
    d_requiredTokens__(0),
    d_acceptedTokens__(d_requiredTokens__),
    d_token__(_UNDETERMINED_),
    d_nextToken__(_UNDETERMINED_)
{}


void interpretParser::print__()
{
// $insert print
}

void interpretParserBase::clearin()
{
    d_token__ = d_nextToken__ = _UNDETERMINED_;
}

void interpretParserBase::push__(size_t state)
{
    if (static_cast<size_t>(d_stackIdx__ + 1) == d_stateStack__.size())
    {
        size_t newSize = d_stackIdx__ + STACK_EXPANSION;
        d_stateStack__.resize(newSize);
        d_valueStack__.resize(newSize);
        // $insert LTYPEresize
        d_locationStack__.resize(newSize);
    }
    ++d_stackIdx__;
    d_stateStack__[d_stackIdx__] = d_state__ = state;
    *(d_vsp__ = &d_valueStack__[d_stackIdx__]) = d_val__;
    // $insert LTYPEpush
    *(d_lsp__ = &d_locationStack__[d_stackIdx__]) = d_loc__;
}

void interpretParserBase::popToken__()
{
    d_token__ = d_nextToken__;

    d_val__ = d_nextVal__;
    d_nextVal__ = STYPE__();

    d_nextToken__ = _UNDETERMINED_;
}
     
void interpretParserBase::pushToken__(int token)
{
    d_nextToken__ = d_token__;
    d_nextVal__ = d_val__;
    d_token__ = token;
}
     
void interpretParserBase::pop__(size_t count)
{
    if (d_stackIdx__ < static_cast<int>(count))
    {
        ABORT();
    }

    d_stackIdx__ -= count;
    d_state__ = d_stateStack__[d_stackIdx__];
    d_vsp__ = &d_valueStack__[d_stackIdx__];
    // $insert LTYPEpop
    d_lsp__ = &d_locationStack__[d_stackIdx__];
}

inline size_t interpretParserBase::top__() const
{
    return d_stateStack__[d_stackIdx__];
}

void interpretParser::executeAction(int production)
try
{
    if (d_token__ != _UNDETERMINED_)
        pushToken__(d_token__);     // save an already available token

                                    // save default non-nested block $$
    if (int size = s_productionInfo[production].d_size)
        d_val__ = d_vsp__[1 - size];

    switch (production)
    {
        // $insert actioncases
        
        case 2:
#line 68 "interpret.y"
        {
         AP_UI val = (*d_vsp__[0].szam);
         std::vector<AP_UC> vec(argmeret);
         Utils::uint2vecc( val, vec );
         if ( d_vsp__[-2].earg->isvalt )
         {
         allapot->set_var( (d_vsp__[-2].earg->elsobyte), vec );
         } else
         {
         allapot->set_reg( (d_vsp__[-2].earg->reg), vec );
         }
         
         delete d_vsp__[-2].earg;
         delete d_vsp__[0].szam;
         }
        break;

        case 3:
#line 85 "interpret.y"
        {
         AP_UI val = (*d_vsp__[0].szam);
         std::vector<AP_UC> vec(argmeret);
         AP_UI plusz;
         if ( d_vsp__[-2].earg->isvalt )
         {
         allapot->get_var( (d_vsp__[-2].earg->elsobyte), argmeret, vec );
         plusz = Utils::vecc2uint( vec );
         val += plusz;
         Utils::uint2vecc( val, vec );
         allapot->set_var( (d_vsp__[-2].earg->elsobyte), vec );
         } else
         {
         allapot->get_reg( (d_vsp__[-2].earg->reg), vec );
         plusz = Utils::vecc2uint( vec );
         val += plusz;
         Utils::uint2vecc( val, vec );
         allapot->set_reg( (d_vsp__[-2].earg->reg), vec );
         }
         allapot->set_zero( val == 0 );
         
         delete d_vsp__[-2].earg;
         delete d_vsp__[0].szam;
         }
        break;

        case 4:
#line 112 "interpret.y"
        {
         AP_UI val = (*d_vsp__[0].szam);
         std::vector<AP_UC> vec(argmeret);
         AP_UI minusz;
         if ( d_vsp__[-2].earg->isvalt )
         {
         allapot->get_var( (d_vsp__[-2].earg->elsobyte), argmeret, vec );
         minusz = Utils::vecc2uint( vec );
         val -= minusz;
         Utils::uint2vecc( val, vec );
         allapot->set_var( (d_vsp__[-2].earg->elsobyte), vec );
         } else
         {
         allapot->get_reg( (d_vsp__[-2].earg->reg), vec );
         minusz = Utils::vecc2uint( vec );
         val -= minusz;
         Utils::uint2vecc( val, vec );
         allapot->set_reg( (d_vsp__[-2].earg->reg), vec );
         }
         allapot->set_sign( val < minusz );
         allapot->set_zero( val == 0 );
         
         delete d_vsp__[-2].earg;
         delete d_vsp__[0].szam;
         }
        break;

        case 5:
#line 139 "interpret.y"
        {
         std::vector<AP_UC> vec;
         AP_UI val1 = (*d_vsp__[-2].szam);
         AP_UI val2 = (*d_vsp__[0].szam);
         
         allapot->set_sign( val1 < val2 );
         allapot->set_zero( (val1 - val2) == 0 );
         
         
         delete d_vsp__[-2].szam;
         delete d_vsp__[0].szam;
         }
        break;

        case 6:
#line 153 "interpret.y"
        {
         AP_UI val = (*d_vsp__[0].szam);
         std::vector<AP_UC> vec(argmeret);
         if ( d_vsp__[-2].earg->isvalt )
         {
         allapot->get_var( (d_vsp__[-2].earg->elsobyte), argmeret, vec );
         val &= Utils::vecc2uint( vec );
         Utils::uint2vecc( val, vec );
         allapot->set_var( (d_vsp__[-2].earg->elsobyte), vec );
         } else
         {
         allapot->get_reg( (d_vsp__[-2].earg->reg), vec );
         val &= Utils::vecc2uint( vec );
         Utils::uint2vecc( val, vec );
         allapot->set_reg( (d_vsp__[-2].earg->reg), vec );
         }
         allapot->set_zero( val == 0 );
         
         delete d_vsp__[-2].earg;
         delete d_vsp__[0].szam;
         }
        break;

        case 7:
#line 176 "interpret.y"
        {
         AP_UI val = (*d_vsp__[0].szam);
         std::vector<AP_UC> vec(argmeret);
         if ( d_vsp__[-2].earg->isvalt )
         {
         allapot->get_var( (d_vsp__[-2].earg->elsobyte), argmeret, vec );
         val |= Utils::vecc2uint( vec );
         Utils::uint2vecc( val, vec );
         allapot->set_var( (d_vsp__[-2].earg->elsobyte), vec );
         } else
         {
         allapot->get_reg( (d_vsp__[-2].earg->reg), vec );
         val |= Utils::vecc2uint( vec );
         Utils::uint2vecc( val, vec );
         allapot->set_reg( (d_vsp__[-2].earg->reg), vec );
         }
         allapot->set_zero( val == 0 );
         
         delete d_vsp__[-2].earg;
         delete d_vsp__[0].szam;
         }
        break;

        case 8:
#line 199 "interpret.y"
        {
         AP_UI val = (*d_vsp__[0].szam);
         std::vector<AP_UC> vec(argmeret);
         if ( d_vsp__[-2].earg->isvalt )
         {
         allapot->get_var( (d_vsp__[-2].earg->elsobyte), argmeret, vec );
         val ^= Utils::vecc2uint( vec );
         Utils::uint2vecc( val, vec );
         allapot->set_var( (d_vsp__[-2].earg->elsobyte), vec );
         } else
         {
         allapot->get_reg( (d_vsp__[-2].earg->reg), vec );
         val ^= Utils::vecc2uint( vec );
         Utils::uint2vecc( val, vec );
         allapot->set_reg( (d_vsp__[-2].earg->reg), vec );
         }
         allapot->set_zero( val == 0 );
         
         delete d_vsp__[-2].earg;
         delete d_vsp__[0].szam;
         }
        break;

        case 9:
#line 222 "interpret.y"
        {
         std::vector<AP_UC> vec;
         AP_UI mulval;
         if ( argmeret == 4 )
         {
         allapot->get_reg( "eax" , vec );
         } else if ( argmeret == 2)
         {
         allapot->get_reg( "ax" , vec );
         } else 
         {
         allapot->get_reg( "al" , vec );
         }
         mulval = Utils::vecc2uint( vec );
         
         AP_UI baseval;
         if ( d_vsp__[0].earg->isvalt )
         {
         allapot->get_var( (d_vsp__[0].earg->elsobyte) , argmeret, vec );
         } else
         {
         allapot->get_reg( (d_vsp__[0].earg->reg), vec );
         }
         baseval = Utils::vecc2uint( vec );
         
         unsigned long result = ((unsigned long) baseval) * ((unsigned long) mulval);
         AP_UI resH = ((result >> 32) & 0xFFFFFFFF);
         AP_UI resL = (result & 0xFFFFFFFF);
         std::vector<AP_UC> vecH(argmeret), vecL(argmeret);
         Utils::uint2vecc( resH, vecH );
         Utils::uint2vecc( resL, vecL );
         
         
         if (argmeret == 4)
         {
         allapot->set_reg("eax", vecL);
         allapot->set_reg("edx", vecH);
         } else if (argmeret == 2)
         {
         allapot->set_reg("ax", vecL);
         allapot->set_reg("dx", vecH);
         } else 
         {
         allapot->set_reg("al", vecL);
         allapot->set_reg("ah", vecH);
         }
         
         delete d_vsp__[0].earg;
         }
        break;

        case 10:
#line 273 "interpret.y"
        {
         std::vector<AP_UC> vecL;
         std::vector<AP_UC> vecH;
         unsigned long divval;
         if ( argmeret == 4 )
         {
         allapot->get_reg( "edx" , vecH );
         allapot->get_reg( "eax" , vecL );
         } else if ( argmeret == 2)
         {
         allapot->get_reg( "dx" , vecH );
         allapot->get_reg( "ax" , vecL );
         } else 
         {
         allapot->get_reg( "ah" , vecH );
         allapot->get_reg( "al" , vecL );
         }
         divval = (Utils::vecc2uint( vecH ) << (argmeret * 4)) | (Utils::vecc2uint(vecL));
         
         std::vector<AP_UC> vec;
         if ( d_vsp__[0].earg->isvalt )
         {
         allapot->get_var( (d_vsp__[0].earg->elsobyte) , argmeret, vec );
         } else
         {
         allapot->get_reg( (d_vsp__[0].earg->reg) , vec );
         }
         AP_UI oszto = Utils::vecc2uint( vec );
         
         AP_UI res = divval / oszto;
         AP_UI rem = divval % oszto;
         
         Utils::uint2vecc( res, vecL );
         Utils::uint2vecc( rem, vecH );
         
         if ( argmeret == 4)
         {
         allapot->set_reg( "edx" , vecH );
         allapot->set_reg( "eax" , vecL );
         } else if (argmeret == 2)
         {
         allapot->set_reg( "dx" , vecH );
         allapot->set_reg( "ax" , vecL );
         } else 
         {
         allapot->set_reg( "ah" , vecH );
         allapot->set_reg( "al" , vecL );
         }
         
         delete d_vsp__[0].earg;
         }
        break;

        case 11:
#line 326 "interpret.y"
        {
         std::vector<AP_UC> vec;
         AP_UI val;
         if ( d_vsp__[0].earg->isvalt )
         {
         allapot->get_var( d_vsp__[0].earg->elsobyte, argmeret, vec );
         val = Utils::vecc2uint( vec );
         ++val;
         Utils::uint2vecc( val, vec );
         allapot->set_var( d_vsp__[0].earg->elsobyte, vec );
         } else
         {
         allapot->get_reg( d_vsp__[0].earg->reg, vec );
         val = Utils::vecc2uint( vec );
         ++val;
         Utils::uint2vecc( val, vec );
         allapot->set_reg( d_vsp__[0].earg->reg, vec );
         }
         allapot->set_zero( val == 0 );
         
         delete d_vsp__[0].earg;
         }
        break;

        case 12:
#line 350 "interpret.y"
        {
         std::vector<AP_UC> vec;
         AP_UI val;
         if ( d_vsp__[0].earg->isvalt )
         {
         allapot->get_var( d_vsp__[0].earg->elsobyte, argmeret, vec );
         val = Utils::vecc2uint( vec );
         --val;
         Utils::uint2vecc( val, vec );
         allapot->set_var( d_vsp__[0].earg->elsobyte, vec );
         } else
         {
         allapot->get_reg( d_vsp__[0].earg->reg, vec );
         val = Utils::vecc2uint( vec );
         --val;
         Utils::uint2vecc( val, vec );
         allapot->set_reg( d_vsp__[0].earg->reg, vec );
         }
         allapot->set_zero( val == 0 );
         
         delete d_vsp__[0].earg;
         }
        break;

        case 13:
#line 374 "interpret.y"
        {
         std::vector<AP_UC> vec;
         AP_UI val;
         if ( d_vsp__[0].earg->isvalt )
         {
         allapot->get_var( d_vsp__[0].earg->elsobyte, argmeret, vec );
         val = Utils::vecc2uint( vec );
         val = ~val;
         Utils::uint2vecc( val, vec );
         allapot->set_var( d_vsp__[0].earg->elsobyte, vec );
         } else
         {
         allapot->get_reg( d_vsp__[0].earg->reg, vec );
         val = Utils::vecc2uint( vec );
         val = ~val;
         Utils::uint2vecc( val, vec );
         allapot->set_reg( d_vsp__[0].earg->reg, vec );
         }
         allapot->set_zero( val == 0 );
         
         delete d_vsp__[0].earg;
         }
        break;

        case 14:
#line 398 "interpret.y"
        {
         std::vector<AP_UC> vec;
         if ( d_vsp__[0].earg-> isvalt )
         {
         allapot->get_var( d_vsp__[0].earg->elsobyte, argmeret, vec );
         } else
         {
         allapot->get_reg( d_vsp__[0].earg->reg, vec );
         }
         allapot->verem_push( vec );
         delete d_vsp__[0].earg;
         }
        break;

        case 15:
#line 412 "interpret.y"
        {
         std::vector<AP_UC> vec;
         allapot->verem_pop( argmeret, vec );
         if ( d_vsp__[0].earg-> isvalt )
         {
         allapot->set_var( d_vsp__[0].earg->elsobyte, vec );
         } else
         {
         allapot->set_reg( d_vsp__[0].earg->reg, vec );
         }
         delete d_vsp__[0].earg;
         }
        break;

        case 16:
#line 426 "interpret.y"
        {
         AP_UI kov = (*ugrocimkek)[*d_vsp__[0].szoveg];
         allapot->set_kovetkezo(kov);
         delete d_vsp__[0].szoveg;
         }
        break;

        case 17:
#line 433 "interpret.y"
        {
         AP_UI kov = (*ugrocimkek)[*d_vsp__[0].szoveg];
         if ( allapot->get_sign() == 0 && allapot->get_zero() == 0 )
         {
         allapot->set_kovetkezo(kov);
         }
         delete d_vsp__[0].szoveg;
         }
        break;

        case 18:
#line 443 "interpret.y"
        {
         AP_UI kov = (*ugrocimkek)[*d_vsp__[0].szoveg];
         if ( allapot->get_sign() == 1 && allapot->get_zero() == 0 )
         {
         allapot->set_kovetkezo(kov);
         }
         delete d_vsp__[0].szoveg;
         }
        break;

        case 19:
#line 453 "interpret.y"
        {
         AP_UI kov = (*ugrocimkek)[*d_vsp__[0].szoveg];
         if ( allapot->get_zero() == 1 )
         {
         allapot->set_kovetkezo(kov);
         }
         delete d_vsp__[0].szoveg;
         }
        break;

        case 20:
#line 463 "interpret.y"
        {
         int kov = (*ugrocimkek)[*d_vsp__[0].szoveg];
         if ( allapot->get_zero() == 1 )
         {
         allapot->set_kovetkezo(kov);
         }
         delete d_vsp__[0].szoveg;
         }
        break;

        case 21:
#line 473 "interpret.y"
        {
         AP_UI kov = (*ugrocimkek)[*d_vsp__[0].szoveg];
         if ( allapot->get_sign() == 1 || allapot->get_zero() == 1 )
         {
         allapot->set_kovetkezo(kov);
         }
         delete d_vsp__[0].szoveg;
         }
        break;

        case 22:
#line 483 "interpret.y"
        {
         AP_UI kov = (*ugrocimkek)[*d_vsp__[0].szoveg];
         if ( allapot->get_sign() == 0 || allapot->get_zero() == 1 )
         {
         allapot->set_kovetkezo(kov);
         }
         delete d_vsp__[0].szoveg;
         }
        break;

        case 23:
#line 493 "interpret.y"
        {
         AP_UI kov = (*ugrocimkek)[*d_vsp__[0].szoveg];
         if ( allapot->get_zero() == 0 )
         {
         allapot->set_kovetkezo(kov);
         }
         delete d_vsp__[0].szoveg;
         }
        break;

        case 24:
#line 503 "interpret.y"
        {
         AP_UI kov = (*ugrocimkek)[*d_vsp__[0].szoveg];
         if ( allapot->get_zero() == 0 )
         {
         allapot->set_kovetkezo(kov);
         }
         delete d_vsp__[0].szoveg;
         }
        break;

        case 25:
#line 513 "interpret.y"
        {
         AP_UI cel = (*ugrocimkek)[*d_vsp__[0].szoveg];
         AP_UI kov = allapot->get_kovetkezo();
         std::vector<AP_UC> vec(4);
         Utils::uint2vecc( kov, vec );
         allapot->verem_push( vec );
         allapot->set_kovetkezo( cel );
         delete d_vsp__[0].szoveg;
         }
        break;

        case 26:
#line 524 "interpret.y"
        {
         std::vector<AP_UC> vec;
         allapot->verem_pop(4, vec);
         AP_UI kov = Utils::vecc2uint( vec );
         allapot->set_kovetkezo( kov );
         }
        break;

        case 27:
#line 534 "interpret.y"
        {
         d_val__.earg = new elso_argumentum( (*d_vsp__[0].szoveg) );
         
         delete d_vsp__[0].szoveg;
         }
        break;

        case 28:
#line 541 "interpret.y"
        {
         d_val__.earg = new elso_argumentum( (*d_vsp__[-1].szam) );
         
         delete d_vsp__[-1].szam;
         }
        break;

        case 29:
#line 550 "interpret.y"
        {
         d_val__.szam = d_vsp__[-1].szam;
         }
        break;

        case 30:
#line 555 "interpret.y"
        {
         d_val__.szam = new AP_UI( (*d_vsp__[-2].szam) * (*d_vsp__[0].szam));
         delete d_vsp__[-2].szam;
         delete d_vsp__[0].szam;
         }
        break;

        case 31:
#line 562 "interpret.y"
        {
         d_val__.szam = new AP_UI( (*d_vsp__[-2].szam) / (*d_vsp__[0].szam));
         delete d_vsp__[-2].szam;
         delete d_vsp__[0].szam;
         }
        break;

        case 32:
#line 569 "interpret.y"
        {
         d_val__.szam = new AP_UI( (*d_vsp__[-2].szam) + (*d_vsp__[0].szam));
         delete d_vsp__[-2].szam;
         delete d_vsp__[0].szam;
         }
        break;

        case 33:
#line 576 "interpret.y"
        {
         d_val__.szam = new AP_UI( (*d_vsp__[-2].szam) - (*d_vsp__[0].szam));
         delete d_vsp__[-2].szam;
         delete d_vsp__[0].szam;
         }
        break;

        case 34:
#line 583 "interpret.y"
        {
         std::vector<AP_UC> reg;
         allapot->get_reg( (*d_vsp__[0].szoveg), reg);
         d_val__.szam = new AP_UI( Utils::vecc2uint(reg) );
         delete d_vsp__[0].szoveg;
         }
        break;

        case 35:
#line 591 "interpret.y"
        {
         d_val__.szam = new AP_UI( allapot->elso_byte( (*d_vsp__[0].szoveg) ));
         delete d_vsp__[0].szoveg;
         }
        break;

        case 36:
#line 597 "interpret.y"
        {
         d_val__.szam = new AP_UI( atoi( d_vsp__[0].szoveg->c_str() ) );
         delete d_vsp__[0].szoveg;
         }
        break;

    }
}
catch (std::exception const &exc)
{
    exceptionHandler__(exc);
}

inline void interpretParserBase::reduce__(PI__ const &pi)
{
    d_token__ = pi.d_nonTerm;
    pop__(pi.d_size);

}

// If d_token__ is _UNDETERMINED_ then if d_nextToken__ is _UNDETERMINED_ another
// token is obtained from lex(). Then d_nextToken__ is assigned to d_token__.
void interpretParser::nextToken()
{
    if (d_token__ != _UNDETERMINED_)        // no need for a token: got one
        return;                             // already

    if (d_nextToken__ != _UNDETERMINED_)
    {
        popToken__();                       // consume pending token
    }
    else
    {
        ++d_acceptedTokens__;               // accept another token (see
                                            // errorRecover())
        d_token__ = lex();
        if (d_token__ <= 0)
            d_token__ = _EOF_;
    }
    print();
}

// if the final transition is negative, then we should reduce by the rule
// given by its positive value. Note that the `recovery' parameter is only
// used with the --debug option
int interpretParser::lookup(bool recovery)
{
// $insert threading
    SR__ *sr = s_state[d_state__];          // get the appropriate state-table
    int lastIdx = sr->d_lastIdx;            // sentinel-index in the SR__ array
    
    SR__ *lastElementPtr = sr + lastIdx;
    lastElementPtr->d_token = d_token__;    // set search-token
    
    SR__ *elementPtr = sr + 1;              // start the search at s_xx[1]
    while (elementPtr->d_token != d_token__)
        ++elementPtr;
    

    if (elementPtr == lastElementPtr)   // reached the last element
    {
        if (elementPtr->d_action < 0)   // default reduction
        {
            return elementPtr->d_action;                
        }

        // No default reduction, so token not found, so error.
        throw UNEXPECTED_TOKEN__;
    }

    // not at the last element: inspect the nature of the action
    // (< 0: reduce, 0: ACCEPT, > 0: shift)

    int action = elementPtr->d_action;


    return action;
}

    // When an error has occurred, pop elements off the stack until the top
    // state has an error-item. If none is found, the default recovery
    // mode (which is to abort) is activated. 
    //
    // If EOF is encountered without being appropriate for the current state,
    // then the error recovery will fall back to the default recovery mode.
    // (i.e., parsing terminates)
void interpretParser::errorRecovery()
try
{
    if (d_acceptedTokens__ >= d_requiredTokens__)// only generate an error-
    {                                           // message if enough tokens 
        ++d_nErrors__;                          // were accepted. Otherwise
        error("Syntax error");                  // simply skip input

    }


    // get the error state
    while (not (s_state[top__()][0].d_type & ERR_ITEM))
    {
        pop__();
    }

    // In the error state, lookup a token allowing us to proceed.
    // Continuation may be possible following multiple reductions,
    // but eventuall a shift will be used, requiring the retrieval of
    // a terminal token. If a retrieved token doesn't match, the catch below 
    // will ensure the next token is requested in the while(true) block
    // implemented below:

    int lastToken = d_token__;                  // give the unexpected token a
                                                // chance to be processed
                                                // again.

    pushToken__(_error_);                       // specify _error_ as next token
    push__(lookup(true));                       // push the error state

    d_token__ = lastToken;                      // reactivate the unexpected
                                                // token (we're now in an
                                                // ERROR state).

    bool gotToken = true;                       // the next token is a terminal

    while (true)
    {
        try
        {
            if (s_state[d_state__]->d_type & REQ_TOKEN)
            {
                gotToken = d_token__ == _UNDETERMINED_;
                nextToken();                    // obtain next token
            }
            
            int action = lookup(true);

            if (action > 0)                 // push a new state
            {
                push__(action);
                popToken__();

                if (gotToken)
                {

                    d_acceptedTokens__ = 0;
                    return;
                }
            }
            else if (action < 0)
            {
                // no actions executed on recovery but save an already 
                // available token:
                if (d_token__ != _UNDETERMINED_)
                    pushToken__(d_token__);
 
                                            // next token is the rule's LHS
                reduce__(s_productionInfo[-action]); 
            }
            else
                ABORT();                    // abort when accepting during
                                            // error recovery
        }
        catch (...)
        {
            if (d_token__ == _EOF_)
                ABORT();                    // saw inappropriate _EOF_
                      
            popToken__();                   // failing token now skipped
        }
    }
}
catch (ErrorRecovery__)       // This is: DEFAULT_RECOVERY_MODE
{
    ABORT();
}

    // The parsing algorithm:
    // Initially, state 0 is pushed on the stack, and d_token__ as well as
    // d_nextToken__ are initialized to _UNDETERMINED_. 
    //
    // Then, in an eternal loop:
    //
    //  1. If a state does not have REQ_TOKEN no token is assigned to
    //     d_token__. If the state has REQ_TOKEN, nextToken() is called to
    //      determine d_nextToken__ and d_token__ is set to
    //     d_nextToken__. nextToken() will not call lex() unless d_nextToken__ is 
    //     _UNDETERMINED_. 
    //
    //  2. lookup() is called: 
    //     d_token__ is stored in the final element's d_token field of the
    //     state's SR_ array. 
    //
    //  3. The current token is looked up in the state's SR_ array
    //
    //  4. Depending on the result of the lookup() function the next state is
    //     shifted on the parser's stack, a reduction by some rule is applied,
    //     or the parsing function returns ACCEPT(). When a reduction is
    //     called for, any action that may have been defined for that
    //     reduction is executed.
    //
    //  5. An error occurs if d_token__ is not found, and the state has no
    //     default reduction. Error handling was described at the top of this
    //     file.

int interpretParser::parse()
try 
{
    push__(0);                              // initial state
    clearin();                              // clear the tokens.

    while (true)
    {
        try
        {
            if (s_state[d_state__]->d_type & REQ_TOKEN)
                nextToken();                // obtain next token


            int action = lookup(false);     // lookup d_token__ in d_state__

            if (action > 0)                 // SHIFT: push a new state
            {
                push__(action);
                popToken__();               // token processed
            }
            else if (action < 0)            // REDUCE: execute and pop.
            {
                executeAction(-action);
                                            // next token is the rule's LHS
                reduce__(s_productionInfo[-action]); 
            }
            else 
                ACCEPT();
        }
        catch (ErrorRecovery__)
        {
            errorRecovery();
        }
    }
}
catch (Return__ retValue)
{
    return retValue;
}



